from enum import Enum

class Status(Enum):
    SUCCESS = "SUCCESS"
    NO_DOCTOR_AVAILABLE = "NO_DOCTOR_AVAILABLE"
    NO_DATE_AVAILABLE_FOR_DOCTOR = "NO_DATE_AVAILABLE_FOR_DOCTOR"
    NO_AVAILABLE_HOURS_ON_DATE = "NO_AVAILABLE_HOURS_ON_DATE"
    BOOKING_FAILED_AT_TIME = "BOOKING_FAILED_AT_TIME"
    BOOKING_SUCCESSFUL = "BOOKING_SUCCESSFUL"
    INVALID_DATE_FORMAT = "INVALID_DATE_FORMAT"